// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../../mocks/outbound/mock_repository.go -package=mocks_outbound
//

// Package mocks_outbound is a generated GoMock package.
package mocks_outbound

import (
	context "context"
	reflect "reflect"

	outbound "github.com/lokalabsmaya/rasia/internal/core/port/outbound"
	repositories "github.com/lokalabsmaya/rasia/internal/core/port/outbound/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DoInTransaction mocks base method.
func (m *MockRepository) DoInTransaction(ctx context.Context, fn func(outbound.Repository) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", ctx, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockRepositoryMockRecorder) DoInTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockRepository)(nil).DoInTransaction), ctx, fn)
}

// GetNamespaceRepository mocks base method.
func (m *MockRepository) GetNamespaceRepository() repositories.Namespace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespaceRepository")
	ret0, _ := ret[0].(repositories.Namespace)
	return ret0
}

// GetNamespaceRepository indicates an expected call of GetNamespaceRepository.
func (mr *MockRepositoryMockRecorder) GetNamespaceRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespaceRepository", reflect.TypeOf((*MockRepository)(nil).GetNamespaceRepository))
}

// GetSecretFileRepository mocks base method.
func (m *MockRepository) GetSecretFileRepository() repositories.SecretFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFileRepository")
	ret0, _ := ret[0].(repositories.SecretFile)
	return ret0
}

// GetSecretFileRepository indicates an expected call of GetSecretFileRepository.
func (mr *MockRepositoryMockRecorder) GetSecretFileRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFileRepository", reflect.TypeOf((*MockRepository)(nil).GetSecretFileRepository))
}

// GetSecretRepository mocks base method.
func (m *MockRepository) GetSecretRepository() repositories.Secret {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretRepository")
	ret0, _ := ret[0].(repositories.Secret)
	return ret0
}

// GetSecretRepository indicates an expected call of GetSecretRepository.
func (mr *MockRepositoryMockRecorder) GetSecretRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretRepository", reflect.TypeOf((*MockRepository)(nil).GetSecretRepository))
}

// GetFileContentRepository mocks base method.
func (m *MockRepository) GetFileContentRepository() repositories.FileContent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContentRepository")
	ret0, _ := ret[0].(repositories.FileContent)
	return ret0
}

// GetFileContentRepository indicates an expected call of GetFileContentRepository.
func (mr *MockRepositoryMockRecorder) GetFileContentRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContentRepository", reflect.TypeOf((*MockRepository)(nil).GetFileContentRepository))
}
