// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/export": {
            "get": {
                "description": "Resolves a namespace path and returns all decrypted files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Export"
                ],
                "summary": "Export Secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace path (e.g. production/application)",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/files/{file_id}/content": {
            "get": {
                "description": "Returns decrypted file content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FileContent"
                ],
                "summary": "Get File Content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResFileContent"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Encrypts and upserts file content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FileContent"
                ],
                "summary": "Save File Content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqSaveFileContent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/files/{file_id}/secrets": {
            "get": {
                "description": "Returns all secrets in a file (values masked)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "List Secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResSecret"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Encrypts and stores a new key-value pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Add Secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Secret data",
                        "name": "secret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqAddSecret"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/files/{id}": {
            "delete": {
                "description": "Soft-deletes a file and its secrets/content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SecretFiles"
                ],
                "summary": "Delete Secret File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/namespaces": {
            "post": {
                "description": "Creates a new namespace node",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Namespaces"
                ],
                "summary": "Create Namespace",
                "parameters": [
                    {
                        "description": "Namespace data",
                        "name": "namespace",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqCreateNamespace"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/namespaces/tree": {
            "get": {
                "description": "Returns the full namespace tree",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Namespaces"
                ],
                "summary": "Get Namespace Tree",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResNamespace"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/namespaces/{id}": {
            "delete": {
                "description": "Soft-deletes a namespace and its descendants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Namespaces"
                ],
                "summary": "Delete Namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/namespaces/{namespace_id}/files": {
            "get": {
                "description": "Returns all files in a namespace",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SecretFiles"
                ],
                "summary": "List Secret Files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResSecretFile"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new file in a namespace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SecretFiles"
                ],
                "summary": "Create Secret File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "File data",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqCreateSecretFile"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/secrets/{id}": {
            "put": {
                "description": "Encrypts and updates an existing key-value pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Update Secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Secret ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Secret data",
                        "name": "secret",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqUpdateSecret"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a secret",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Delete Secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Secret ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/api/secrets/{id}/reveal": {
            "get": {
                "description": "Decrypts and returns the plaintext value",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secrets"
                ],
                "summary": "Reveal Secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Secret ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResRevealSecret"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.SecretFileExt": {
            "type": "string",
            "enum": [
                "env",
                "yaml",
                "json",
                "txt"
            ],
            "x-enum-varnames": [
                "SecretFileExtEnv",
                "SecretFileExtYAML",
                "SecretFileExtJSON",
                "SecretFileExtTXT"
            ]
        },
        "dto.ReqAddSecret": {
            "type": "object",
            "required": [
                "key_name",
                "value"
            ],
            "properties": {
                "key_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.ReqCreateNamespace": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "parent_id": {
                    "type": "string"
                }
            }
        },
        "dto.ReqCreateSecretFile": {
            "type": "object",
            "required": [
                "ext",
                "name"
            ],
            "properties": {
                "ext": {
                    "enum": [
                        "env",
                        "yaml",
                        "json",
                        "txt"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.SecretFileExt"
                        }
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "dto.ReqSaveFileContent": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "dto.ReqUpdateSecret": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.ResFileContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "dto.ResNamespace": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResNamespace"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ResRevealSecret": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.ResSecret": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "file_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ResSecretFile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "ext": {
                    "$ref": "#/definitions/domain.SecretFileExt"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "pagination.Result": {
            "type": "object",
            "properties": {
                "cursor": {
                    "$ref": "#/definitions/pagination.ResultPaginationCursor"
                },
                "offset": {
                    "$ref": "#/definitions/pagination.ResultPaginationOffset"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "pagination.ResultPaginationCursor": {
            "type": "object",
            "properties": {
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                },
                "total_data": {
                    "type": "integer"
                }
            }
        },
        "pagination.ResultPaginationOffset": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_data": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "response.Metadata": {
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/pagination.Result"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "response.ResponseSuccess": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "metadata": {
                    "$ref": "#/definitions/response.Metadata"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "rasia Service API",
	Description:      "This is a documentation for rasia Service RESTful APIs. <br>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
